---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: This is a basic example application
  tags:
    - observability-stack
    - prometheus
    - grafana
    - monitoring
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}'
    backstage.io/kubernetes-namespace: default
    argocd/app-name: ${{values.name | dump}}
  links:
    - url: https://github.com/${{values.githubOrg}}/${{values.githubRepoName}}
      title: Repo URL
      icon: github
    - url: https://grafana.${{values.name}}.${{values.domain}}
      title: Grafana URL
      icon: dashboard
spec:
  owner: guests
  lifecycle: experimental
  type: service
  system: ${{values.name | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.name | dump}}
  description: An example system for demonstration purposes
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: guests
  lifecycle: experimental
  type: service
  stackType: observability-stack
