site_name: ${{values.name}}
site_description: Java Spring boot app with prometheus and loki integration

nav:
  - Home: index.md
  - Bit√°cora del Experimento: Bitacora.md

plugins:
  - techdocs-core
