---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: This is a python + flask app with prometheus-ready endpoint
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'entity-id=${{values.name}}'
    backstage.io/kubernetes-namespace: default
    argocd/app-name: ${{values.name | dump}}
  links:
    - url: https://github.com/${{values.githubOrg}}/${{values.githubRepoName}}
      title: Repo URL
      icon: github
    - url: https://${{values.name}}.${{values.parentSystem}}.${{values.domain}}
      title: Url Shortener App 
      icon: externalLink
spec:
  owner: guests
  lifecycle: experimental
  type: service
  system: ${{values.parentSystem | dump}}
